/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as DonateSuccessRouteImport } from './routes/donate.success'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminStripeRouteImport } from './routes/_authenticated/admin.stripe'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin.email'
import { Route as AuthenticatedAdminDonationsRouteImport } from './routes/_authenticated/admin.donations'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const DonateSuccessRoute = DonateSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DonateRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminStripeRoute =
  AuthenticatedAdminStripeRouteImport.update({
    id: '/stripe',
    path: '/stripe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDonationsRoute =
  AuthenticatedAdminDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate': typeof DonateRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/signup': typeof SignupRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/donate/success': typeof DonateSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/stripe': typeof AuthenticatedAdminStripeRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate': typeof DonateRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/signup': typeof SignupRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/donate/success': typeof DonateSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/stripe': typeof AuthenticatedAdminStripeRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/donate': typeof DonateRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/signup': typeof SignupRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/donate/success': typeof DonateSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/_authenticated/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/stripe': typeof AuthenticatedAdminStripeRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donate'
    | '/login'
    | '/projects'
    | '/signup'
    | '/transparency'
    | '/volunteer'
    | '/account'
    | '/admin'
    | '/donate/success'
    | '/projects/$slug'
    | '/admin/donations'
    | '/admin/email'
    | '/admin/reports'
    | '/admin/stripe'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donate'
    | '/login'
    | '/projects'
    | '/signup'
    | '/transparency'
    | '/volunteer'
    | '/account'
    | '/admin'
    | '/donate/success'
    | '/projects/$slug'
    | '/admin/donations'
    | '/admin/email'
    | '/admin/reports'
    | '/admin/stripe'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/donate'
    | '/login'
    | '/projects'
    | '/signup'
    | '/transparency'
    | '/volunteer'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/donate/success'
    | '/projects/$slug'
    | '/_authenticated/admin/donations'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/stripe'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DonateRoute: typeof DonateRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SignupRoute: typeof SignupRoute
  TransparencyRoute: typeof TransparencyRoute
  VolunteerRoute: typeof VolunteerRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/donate/success': {
      id: '/donate/success'
      path: '/success'
      fullPath: '/donate/success'
      preLoaderRoute: typeof DonateSuccessRouteImport
      parentRoute: typeof DonateRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/stripe': {
      id: '/_authenticated/admin/stripe'
      path: '/stripe'
      fullPath: '/admin/stripe'
      preLoaderRoute: typeof AuthenticatedAdminStripeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/donations': {
      id: '/_authenticated/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AuthenticatedAdminDonationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDonationsRoute: typeof AuthenticatedAdminDonationsRoute
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminStripeRoute: typeof AuthenticatedAdminStripeRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDonationsRoute: AuthenticatedAdminDonationsRoute,
  AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminStripeRoute: AuthenticatedAdminStripeRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DonateRouteChildren {
  DonateSuccessRoute: typeof DonateSuccessRoute
}

const DonateRouteChildren: DonateRouteChildren = {
  DonateSuccessRoute: DonateSuccessRoute,
}

const DonateRouteWithChildren =
  DonateRoute._addFileChildren(DonateRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DonateRoute: DonateRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SignupRoute: SignupRoute,
  TransparencyRoute: TransparencyRoute,
  VolunteerRoute: VolunteerRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
